name: Run tests

on:
  push:
    branches: ["*"]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm i -g typescript
          npm i

      - name: Run tests
        run: npm run test
